# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxdHorariodetalle',
            fields=[
                ('idhorariodetalle', models.AutoField(db_column='idHorarioDetalle', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('bus', models.ForeignKey(db_column='Bus_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TxdBus')),
                ('chofer', models.ForeignKey(db_column='Chofer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TxdChofer')),
                ('horario', models.ForeignKey(db_column='Horario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TxdHorario')),
            ],
            options={
                'db_table': 'txd_horariodetalle',
            },
        ),
        migrations.RemoveField(
            model_name='txddiahorario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='txddiahorario',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='txddiahorariodetalle',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='txddiahorariodetalle',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='txddiahorariodetalle',
            name='diahorario',
        ),
        migrations.DeleteModel(
            name='TxdDia',
        ),
        migrations.DeleteModel(
            name='TxdDiahorario',
        ),
        migrations.DeleteModel(
            name='TxdDiahorariodetalle',
        ),
    ]
